The_gossip_project/config/routes.rb
Rails.application.routes.draw do
 root to: 'gossip#index'

  get '/contact', to: 'user#contact'
  get '/team', to: 'user#team'
  get '/welcome/:first_name' , to: 'pages#index_logged', as: 'index_logged'
  get '/session/index', to: 'session#index'

  resources :session, only: [:create, :new, :destroy]
  resources :gossip 
  resources :user
  resources :city

end

The_gossip_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

The_gossip_project/app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

The_gossip_project/app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :gossipp
end

The_gossip_project/app/models/gossipp.rb
class Gossipp < ApplicationRecord
	belongs_to :user
	has_many :joins
	has_many :comments
	has_many :tags, through: :joins
end

The_gossip_project/app/models/join.rb
class Join < ApplicationRecord
	belongs_to :tag
	belongs_to :gossipp
end

The_gossip_project/app/models/like.rb
class Like < ApplicationRecord
end

The_gossip_project/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

The_gossip_project/app/models/tag.rb
class Tag < ApplicationRecord
	has_many :joins
	has_many :gossipps, through: :joins
end

The_gossip_project/app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossipps
	has_many :comments
	has_many :likes
	has_secure_password


	#MP
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

The_gossip_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

The_gossip_project/app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @gossip = City.find(params[:id])
  end
 end

The_gossip_project/app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index

   @gossips = Gossipp.all
  	
  end
  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @gossip = Gossipp.find(params[:id])

  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossipp.new
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    user =User.find(2)
    @gossip = Gossipp.new(title:params[:title],content:params[:content],user_id:user.id)
    if 
      @gossip.save
      redirect_to '/gossip'
      
    else
      render :new
      
    end

    @gossip = Gossipp.create[:id]
  @gossip = User.find_by(id: session[:user_id])
    if @gossip
    flash[:success] = "Potin bien créé !"
    redirect_to root_path
   
    end
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Gossipp.find(params[:id])
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    user = User.find(2)
    @gossip = Gossipp.find(params[:id])
    @gossip.update(title: params[:title], content: params[:content])
    redirect_to '/gossip'
 end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossip_path
  end
end

The_gossip_project/app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :valid_user, only: [:destroy]
  def index

  end

  def create
    user = User.find_by(email: params[:email])
  
    if user && user.authenticate(params[:password])
      log_in(user)
      flash[:success] = 'Connexion réussi'
      redirect_to gossips_path
  
    else
      flash.now[:danger] = 'Invalid email/password combination'
    end
  end


  def destroy
    session.delete(:user_id)
    flash[:success] = 'Deconnexion réussi'
    redirect_to gossips_path
  end
  
end

The_gossip_project/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def contact

  end

  def team

  end
  def edit
  	
  end
  def show
  	
  end
end

The_gossip_project/app/helpers/application_helper.rb
module ApplicationHelper
end

The_gossip_project/app/helpers/contact_helper.rb
module ContactHelper
end

The_gossip_project/app/helpers/gos_helper.rb
module GosHelper
end

The_gossip_project/app/helpers/gossip_helper.rb
module GossipHelper
end

The_gossip_project/app/helpers/session_helper.rb
module SessionHelper
end

The_gossip_project/app/helpers/show_helper.rb
module ShowHelper
end

The_gossip_project/app/helpers/team_helper.rb
module TeamHelper
end

The_gossip_project/app/helpers/user_helper.rb
module UserHelper
end

The_gossip_project/app/views/city/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>city</title>
</head>
<body><center>
	<%= @gossip.name %><br>
	<%=  @gossip.zip_code%>
</center>

</body>
</html>

The_gossip_project/app/views/gossip/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>EDIT</title>
</head>
<body>
 <div class="container">
    <%= form_tag url_for(action: 'update'), method: "PUT" do  %>

      <%= label_tag 'title' %>
      <%= text_field_tag 'title',@gossip.title %>
      <br /> <br />

      <%= label_tag 'content'%>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />


      <%= submit_tag "validate gossip" %>
    <% end %>

	</div>

</body>
</html>

The_gossip_project/app/views/gossip/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="container">
		<div class="card text-center">
	   <% @gossips.each do |gossip| %>
     <div class="card-header">
  	  <% gossip.user.first_name %>
     </div>
      <div class="card-body">
       <h5 class="card-title"><%= gossip.title%></h5>
       <h5 class="card-text"><%= gossip.content%></h5>
       <a href= "<%= gossip_path(gossip.id)%>" class="btn btn-primary">show</a>
        <a href= "<%= edit_gossip_path(gossip.id)%>" class="btn btn-primary">Edit</a>
        <a href= "<%= gossip_index_path(gossip.id)%>" class="btn btn-danger">supprimer</a>
      </div>
    <%end%>
 </div>
	
</body>
</html>

The_gossip_project/app/views/gossip/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <div class="container">
    <%= form_tag url_for(action: 'create'), method: "post" do%>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
        <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @gossip.title, class: 'form-control'%>
    </div>
    <div class="form-group">
        <%= label_tag 'Content' %>
        <%= text_area_tag 'content', @gossip.content, class: 'form-control'%><br>
    </div>
    <div class="form-group">    
     <%= submit_tag "Create Gossip" , class: 'btn btn-primary btn-xs'%> <br><br>
    </div>
<% end %>
<% if @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
 <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
</div>
<ul>
   <% @gossip.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
 </ul>
<% end %>
</body>
</html>

The_gossip_project/app/views/gossip/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
</head>
<body><center>
	<div class="card" style="width: 18rem;">
  <img class="card-img-top" src= url(https://cdn.pixabay.com/photo/2018/10/14/13/01/ruin-3746423_960_720.jpg) alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"> <%= @gossip.user.first_name %> </h5>
    <p class="card-text"> <%= @gossip.content %></p>
    <p class="card-text"><%= @gossip.user.email%></p>
    <a href="<%= gossip_path(@gossip.user.id)%>"> city </a>
    <a href="<%= gossip_index_path%>" class="btn btn-primary">home</a>
    <a href="<%= gossip_path(@gossip.id)%>"
    <span class="btn btn-danger" data-confirm="êtes vous sur!?" data-method ="DELETE">	; </span>
  </div>
</div>
</div>
</center>
</body>
</html>

The_gossip_project/app/views/session/index.html.erb
<h1>Bienvenue, veuillez indiquer vos identifiants de connexion</h1>

<%= form_tag url_for(action: 'create'), method: "post" do %>

    <%= label_tag 'Veuillez indiquer votre email' %>
    <%= text_field_tag 'email',nil, class: 'form-control' %>
    <br /> <br />

    <%= label_tag 'Mot de passe' %>
    <%= password_field_tag 'password',nil, class: 'form-control' %>
    <br /> <br />

    <%= submit_tag "Valider l'inscription ", class: 'btn btn-primary'%>

<% end %>

The_gossip_project/app/views/session/profile.html.erb
<h2>Bienvenue <%= User.find_by(id: session[:user_id]).first_name %> !</h2>

The_gossip_project/app/views/user/contact.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	
</head>

<body><center>
	<h1>Notre contact:</h1>
	 <p>nom : safidy</p>
	 <p>tel : +2610349543592</p>
	 <p><em>email : safidypatrick8@gmail.com</em></p>
	 </center>
</body>
</html>

The_gossip_project/app/views/user/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<p>qjcqsjccqi</p>

</body>
</html>

The_gossip_project/app/views/user/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body><center>
	<h4>votre identiter</h4>
	<p class="card-text"><%= @user.first_name%></p>
</center>


</body>
</html>

The_gossip_project/app/views/user/team.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body><center>
	<p>MY TEAM </p>
	  <p>safidy patrick</p><br>
	  <p>walter</p>
	  </center>

</body>
</html>