The_gossip_project/config/routes.rb
Rails.application.routes.draw do
 root to: 'gossip#index'

  get '/contact', to: 'user#contact'
  get '/team', to: 'user#team'
  get '/welcome/:first_name' , to: 'pages#index_logged', as: 'index_logged'
  get '/session/index', to: 'session#index'

  resources :session, only: [:create, :new, :destroy]
  resources :gossip 
  resources :user
  resources :city

end

The_gossip_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

The_gossip_project/app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

The_gossip_project/app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :gossipp
end

The_gossip_project/app/models/gossipp.rb
class Gossipp < ApplicationRecord
	belongs_to :user
	has_many :joins
	has_many :comments
	has_many :tags, through: :joins
end

The_gossip_project/app/models/join.rb
class Join < ApplicationRecord
	belongs_to :tag
	belongs_to :gossipp
end

The_gossip_project/app/models/like.rb
class Like < ApplicationRecord
end

The_gossip_project/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

The_gossip_project/app/models/tag.rb
class Tag < ApplicationRecord
	has_many :joins
	has_many :gossipps, through: :joins
end

The_gossip_project/app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossipps
	has_many :comments
	has_many :likes
	has_secure_password


	#MP
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

The_gossip_project/app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @gossip = City.find(params[:id])
  end
 end

The_gossip_project/app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index

   @gossips = Gossipp.all
  	
  end
  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @gossip = Gossipp.find(params[:id])

  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossipp.new
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    user =User.find(2)
    @gossip = Gossipp.new(title:params[:title],content:params[:content],user_id:user.id)
    if 
      @gossip.save
      redirect_to '/gossip'
      
    else
      render :new
      
    end

    @gossip = Gossipp.create[:id]
  @gossip = User.find_by(id: session[:user_id])
    if @gossip
    flash[:success] = "Potin bien créé !"
    redirect_to root_path
   
    end
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Gossipp.find(params[:id])
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    user = User.find(2)
    @gossip = Gossipp.find(params[:id])
    @gossip.update(title: params[:title], content: params[:content])
    redirect_to '/gossip'
 end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossip_path
  end
end

The_gossip_project/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def contact

  end

  def team

  end
  def edit
  	
  end
  def show
  	
  end
end

The_gossip_project/app/helpers/application_helper.rb
module ApplicationHelper
end

The_gossip_project/app/helpers/contact_helper.rb
module ContactHelper
end

The_gossip_project/app/helpers/gos_helper.rb
module GosHelper
end

The_gossip_project/app/helpers/gossip_helper.rb
module GossipHelper
end

The_gossip_project/app/helpers/session_helper.rb
module SessionHelper
end

The_gossip_project/app/helpers/show_helper.rb
module ShowHelper
end

The_gossip_project/app/helpers/team_helper.rb
module TeamHelper
end

The_gossip_project/app/helpers/user_helper.rb
module UserHelper
end

The_gossip_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>BIENVENUE DANS NOTRE GOSSIP</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%=link_to "GOSSIP", gossip_index_path %>
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <%=link_to "contact", contact_path %><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
             <%=link_to "team", team_path %>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
             <%=link_to "Créer Potin", new_gossip_path %>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
             <%=link_to "s'identifier", session_index_path %>

  </div>
</nav>
    
  <%= yield %>
</body>
</html>